# Site settings

title: Gatij Blog

SEOTitle: Gatij Blog | Learn in Space and Time
header-img: img/home-bg-spirit.jpg
email: gatijjain@gmail.com

description: "DS & Algo Lover ，Django Developer，Software Engineer，ML Enthusiast "

keyword: "gatijpro, @gatijpro,Gatij Blog,Web,Python,ML,Algorithms"

url: "https://gatijjain.me"              
# your host, for absolute URL
baseurl: ""                             
# for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true


# SNS settings

RSS: false

#weibo_username:     huxpro

#zhihu_username:     huxpro

github_username:     gatij

#twitter_username:   huxpro

#facebook_username:  gatij

linkedin_username:  gatij-jain-385922119



# Build settings

# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.

highlighter: rouge

permalink: pretty

paginate: 10

exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]

anchorjs: true                          
# if you want to customize anchor. check out line:181 of `post.html`

# If you have timezone issue (e.g. #68) in China, uncomment to use this:

#timezone: CN  




# Gems

# from PR
#40, to support local preview for Jekyll 3.0

# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]




# Markdown settings

# replace redcarpet to kramdown,

# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown

# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            
# use Github Flavored Markdown !important




# Disqus settings
disqus_username: gatijjain

# Netease settings

netease_comment: false




# Analytics settings

# Baidu Analytics 

# ba_track_id: [your track id]


# Google Analytics
ga_track_id: 'UA-49627206-1'            
# Format: UA-xxxxxx-xx

ga_domain: gatijjain.me




# Sidebar settings

sidebar: true                           
# whether or not using Sidebar.

sidebar-about-description: "Algorithimist, Software Developer<br>Quick Learner<br>Poet and Public Speaker"
sidebar-avatar: /img/avatar-gatijw-ny.jpeg        
# use absolute URL, seeing it's used in both `/` and `/about/`




# Featured Tags

featured-tags: true                     
# whether or not using Feature-Tags

featured-condition-size: 1              
# A tag will be featured if the size of it is more than this condition value




# Progressive Web Apps
chrome-tab-theme-color: "#000000"

service-worker: true




# Friends
friends: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{
        title: "Rakesh Kumar",
        href: "https://www.linkedin.com/in/rakeshkumar235/"
    },{
        title: "Shashank Bothra",
        href: "https://www.linkedin.com/in/shashank-bothra-01/"
    },{
        title: "Gagan Jain",
        href: "https://www.linkedin.com/in/gaganjain232/"
    }
]
